
name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip codecov pipenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        pipenv run flake8 .

    - name: Test with pytest
      run: |
        pipenv run pytest --cov=pytoolstest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 816b5858-2c49-412e-95ca-f9c2c9495053
